import React, {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import '@fontsource-variable/dm-sans';
import {ArrowUpRight,RotateCw,Search,Upload,Grid2X2} from 'lucide-react';
import './style.css';
const categories=[['all','All inventory'],['bedding','Bedding'],['living-space','Living space'],['decor','Decor']];
function App(){
 const [products,setProducts]=useState([]),[category,setCategory]=useState('all'),[search,setSearch]=useState(''),[pending,setPending]=useState({}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[importing,setImporting]=useState(false);
 async function load(){try{const r=await fetch('/api/products');if(!r.ok)throw Error('Inventory could not be loaded.');setProducts((await r.json()).products);setError('');}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function adjust(p,delta){if(pending[p.id])return;setPending(x=>({...x,[p.id]:true}));setError('');setNotice('');setProducts(xs=>xs.map(x=>x.id===p.id?{...x,current_stock:x.current_stock+delta,reorder_alert:x.current_stock+delta<=x.reorder_level}:x));
 try{const r=await fetch(`/api/products/${p.id}/stock`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({delta,expectedVersion:p.version,requestId:crypto.randomUUID()})});const data=await r.json();if(!r.ok){setProducts(xs=>xs.map(x=>x.id===p.id?(data.product||p):x));throw Error(data.error||'Stock update failed.')}setProducts(xs=>xs.map(x=>x.id===p.id?data.product:x));setNotice(`${p.name}: ${data.product.current_stock} units in stock.`)}catch(e){setProducts(xs=>xs.map(x=>x.id===p.id&&x.version===p.version?p:x));setNotice('');setError(e.message+' Refresh inventory before retrying.')}finally{setPending(x=>({...x,[p.id]:false}))}}
 async function importFile(event){const file=event.target.files?.[0];if(!file)return;setImporting(true);setError('');setNotice('');const form=new FormData();form.append('file',file);try{const response=await fetch('/excel/import',{method:'POST',body:form});const data=await response.json();if(!response.ok)throw Error(data.detail||'Import failed');await load();setNotice(`Imported ${data.imported} product variants.`)}catch(e){setError(e.message)}finally{setImporting(false);event.target.value=''}}
 const visible=products.filter(p=>(category==='all'||p.category===category)&&`${p.name} ${p.sku} ${p.fabric_type} ${p.dimensions}`.toLowerCase().includes(search.toLowerCase()));
 const low=products.filter(p=>p.reorder_alert).length;
 return <div className="shell"><aside><a className="brand" href="#">e<span>·</span>depo<span className="brand-square"><ArrowUpRight size={22}/></span></a><div className="workspace"><span className="avatar">N</span><div>Nuka Selection<small>Mitrovica · Since 1952</small></div></div><p className="nav-label">WORKSPACE</p><a className="nav active" href="#"><Grid2X2 size={18}/> <span>Inventory</span><span><ArrowUpRight size={14}/></span></a><div className="aside-note"><span className="live-dot"/> LIVE DEMO<p>Less spreadsheet.<br/>More possibility.</p><small>Built by Team Avengers<br/>Eren · Inara · Ari</small></div><footer>KosICT 2026 <span>15th edition</span></footer></aside>
 <main><header><div className="breadcrumb">WORKSPACE <span>/</span> INVENTORY</div><span className="owner"><span className="avatar small">F</span> Fisnik <span className="owner-tag">OWNER</span></span></header><section className="heading"><div><p className="eyebrow">EVERY ITEM. ONE CLEAR VIEW.</p><h1>Inventory<span className="title-dot">.</span></h1><p className="subtitle">A little less admin. A lot more room to grow.</p></div><div className="heading-actions"><label className="import-button"><Upload size={14}/>{importing?'Importing…':'Import Excel'}<input type="file" accept=".xlsx" aria-label="Import Excel inventory" disabled={importing} onChange={importFile}/></label><button className="refresh" disabled={Object.values(pending).some(Boolean)||importing} onClick={load}><RotateCw size={14}/> Refresh inventory</button></div></section>
 <section className="metrics" aria-label="Inventory summary"><div><span>PRODUCT VARIANTS</span><strong>{products.length.toString().padStart(2,'0')}</strong><small>Across your collection</small></div><div><span>UNITS IN STOCK</span><strong>{products.reduce((sum,p)=>sum+p.current_stock,0)}</strong><small>Ready for their next home</small></div><div className="warning"><span>NEEDS ATTENTION</span><strong>{low.toString().padStart(2,'0')} <em><ArrowUpRight size={24}/></em></strong><small>At or below reorder level</small></div></section>
 <section className="inventory-panel"><div className="panel-top"><h2>Your collection <span>{visible.length}</span></h2><span className="live-label"><span className="live-dot"/> Connected inventory</span></div><div className="tools"><nav className="tabs" aria-label="Category filters">{categories.map(([key,label])=><button key={key} className={category===key?'selected':''} aria-pressed={category===key} onClick={()=>setCategory(key)}>{label}</button>)}</nav><label className="search"><Search size={15} aria-hidden="true"/><input aria-label="Search inventory" placeholder="Search products, SKU, fabric…" value={search} onChange={e=>setSearch(e.target.value)}/><span>↵</span></label></div>
 {error&&<div className="error" role="alert">{error}</div>}<p className={notice?"notice":"sr-only"} role="status">{notice}</p>
 <div className="table-scroll"><table><thead><tr><th>PRODUCT / SKU</th><th>FABRIC & DIMENSIONS</th><th>STOCK LEVEL</th><th>QUICK ACTION</th></tr></thead><tbody>{visible.map(p=><tr key={p.id}><td><div className="product"><span className={'product-icon '+p.category}>{p.category==='bedding'?'▤':p.category==='living-space'?'▥':'◈'}</span><div><strong>{p.name}</strong><small>{p.sku}</small></div></div></td><td><span className="fabric">{p.fabric_type||'—'}</span><small>{p.dimensions||'—'}</small></td><td><div className="stock"><strong>{p.current_stock}</strong><span className={p.reorder_alert?'low':'healthy'}>{p.reorder_alert?'Low stock':'In stock'}</span></div><small>Reorder at {p.reorder_level} units</small></td><td><div className="actions"><button aria-label={`Add one ${p.name}`} disabled={pending[p.id]} onClick={()=>adjust(p,1)}>+1</button><button className="sell" aria-label={`Sell one ${p.name}`} disabled={pending[p.id]||p.current_stock===0} onClick={()=>adjust(p,-1)}>{pending[p.id]?'Saving…':'Sell one'} <span><ArrowUpRight size={14}/></span></button></div></td></tr>)}</tbody></table></div>
 {loading&&<p className="empty">Loading your collection…</p>}{!loading&&visible.length===0&&<p className="empty">No matching products. Try another search or category.</p>}<div className="table-footer"><span>{visible.length} variants shown · Stock tracked by SKU</span><span>One click. Updated instantly.</span></div></section><div className="bottom"><span>Made for the way Nuka works.</span><span>TEAM AVENGERS <b>✦</b> FUTURE DEVELOPER CORNER</span></div></main></div>
}
createRoot(document.getElementById('root')).render(<App/>);
